### ISSUE TITLE
Not clear if a checkbox/radio is checked when printed

### ISSUE THREAD

**Issue by MartijnCuppens** [tailwindcss/custom-forms#13]
It's not clear whether a checkbox/radio is checked when it is printed and background graphics are disabled (default setting):

![image](https://user-images.githubusercontent.com/11559216/58576821-70e63480-8245-11e9-840d-dc7e11620e28.png)

![image](https://user-images.githubusercontent.com/11559216/58576834-7b083300-8245-11e9-8bc5-7ddc25be8a87.png)

It's fixable with `-webkit-print-color-adjust: exact;` for webkit, but I don't think there's a quick solution for other browsers.

I guess wrapping the custom checkbox/ in a `@media not print {}` query would be the easiest solution, although this would break the sizing (whitespace where the checkbox should be).

Or we could add something like
```
@media print {
  .form-checkbox {
    appearance: checkbox;
    width: auto !important;
    height: auto !important;
  }

  .form-radio {
    appearance: radio;
    width: auto !important;
    height: auto !important;
  }
}
// I tried combining the selectors and use `appearance: initial`, but that didn't work
```
to force normal checkboxes/radios for print and disable the sized checkboxes.

Possibly we'll need something alike for the custom select.

**Comment by adamwathan** [comment]
Bummer, this might be a hard one to fix. I noticed even with no background image even just a regular background color isn't preserved on print, which is a bit surprising 🤔 

Wonder if we could do something with pseudo-elements — I know technically `input` elements aren't supposed to have before/after elements according to the spec but I wonder what happens in practice across browsers if you do it?

**Comment by MartijnCuppens** [comment]
Interesting: https://codepen.io/MartijnCuppens/pen/ZNqzqq

But it doesn't seem to work in IE. Shall have a look if I can find a solution for that later this week.

**Comment by jpscharf** [comment]
What about highlighting the selected checkboxes, or radio.
```css
@media print {
        input[type=radio]:checked:before {
            border-radius: inherit;
            border-width: 5px;
            border-color: black;
            border-style: solid;
            height: 100%;
            width: 100%;
            content: '';
            display: block;
        }

        input[type=radio].form-radio:checked {
            background-color: transparent;
            border-color: transparent;
            background-image: none;
        }

        input[type=checkbox]:checked:before {
            border-radius: inherit;
            border-width: 5px;
            border-color: black;
            border-style: solid;
            height: 100%;
            width: 100%;
            display: block;
            content: '';
        }

        input[type=checkbox].form-checkbox:checked {
            background-color: transparent;
            border-color: transparent;
            background-image: none;
        }
    }
```
