### ISSUE TITLE
Consider having consistent heights

### ISSUE THREAD

**Issue by Larsklopstra** [tailwindcss/custom-forms#58]
In regards to your Tailwind UI newsletter

> Tailwind UI Update #6: Everything you ever (never?) wanted to know about sizing form controls

**Comment by imacrayon** [comment]
I think this could solve issue #43 as well

**Comment by hmaesta** [comment]
Upvote.

I am doing a hard workaround for some buttons that only has an icon and needs to be aligned with buttons with text.

```css
.button {
   @apply leading-tight py-2 (...)

   &.icon-only {
      min-height: calc(1.375rem + theme('padding.2') * 2);
   }
```
